### ISSUE TITLE
backend/src/main.rs/:48:1

### ISSUE THREAD

**Issue by userom11** [TheAnonymousCrusher/Yin-Yang#1]
for word in words
^^^ expected item

error: could not compile `backend` (bin "backend") due to previous error

**Comment by MapikitlaSibongile** [comment]
What's the problem? I don't see it.

**Comment by TheAnonymousCrusher** [comment]
> What's the problem? I don't see it.

I think it should be ```words``` not  ```word```.

**Comment by TheAnonymousCrusher** [comment]
I fixed the issue.
